apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2shop
  labels:
    app: ec2shop
  namespace: opty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec2shop
  template:
    metadata:
      labels:
        app: ec2shop
    spec:
      containers:
      - name: app
        image: yeospace/ec2shop:${rev}
        ports:
        - containerPort: 6000
        env:
        - name: BIND_TO
          value: "0.0.0.0:6000"
        volumeMounts:
          - mountPath: /etc/ssl
            name: ssl-cert
      volumes:
        - name: ssl-cert
          hostPath:
            path: /etc/ssl
